-- snort.conf Snort 3 — NIM: 101032300137
-- Fix: checksum offloading + DAQ afpacket

HOME_NET = 'any'
EXTERNAL_NET = 'any'

-- Disable checksum validation (wajib untuk Docker bridge traffic)
stream = { show_rebuilt_packets = false }

-- DAQ config — gunakan afpacket bukan pcap default
daq =
{
    module = 'afpacket',
    snaplen = 65535,
    variables =
    {
        'buffer_size_mb=128'
    }
}

-- Disable checksum di decoder
-- ini mencegah Snort drop packet dengan offloaded checksum
normalizer =
{
    tcp =
    {
        block = false
    }
}

-- IPS rules
ips =
{
    include = '/etc/snort/rules/local.rules',
    enable_builtin_rules = true
}

-- Output alert
alert_fast =
{
    file = true,
    packet = false
}

-- Log ke file
event_queue =
{
    max_queue = 8,
    log = 8,
    order_events = 'priority'
}