-- ══════════════════════════════════════════════════════════════
-- snort.conf — Snort 3 (Lua) Configuration
-- NIM: 101032300137
-- ══════════════════════════════════════════════════════════════

HOME_NET = 'any'
EXTERNAL_NET = 'any'

ips =
{
    include = '/etc/snort/rules/local.rules'
}

-- Output alert ke stdout (file = false)
-- Entrypoint akan pipe ke file via tee
alert_fast =
{
    file = false,
    packet = false
}
