# ══════════════════════════════════════════════════════════════
# snort.conf — Snort 2.9 Configuration
# NIM: 101032300137
# ══════════════════════════════════════════════════════════════

var HOME_NET any
var EXTERNAL_NET any

include /etc/snort/rules/local.rules